; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino

board_build.psram = enabled
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi

lib_deps = espressif/esp32-camera
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_type = debug
; Crucial for S3 Camera stability
build_flags = 
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=5    ; This will give you more detail if it fails again

; This tells the compiler to use the high-speed PSRAM on your R8 module
